version: "3"

services:
    backend:
        depends_on:
            - db

    nginx:
        depends_on:
            - backend
            - placeholder
            - db
        volumes:
            - certbot-etc:/etc/letsencrypt:ro

    certbot:
        depends_on:
            - nginx

    worker:
        depends_on:
            - nginx
            - certbot

secrets:
    DB_USERNAME:
        file: /srv/vxnn/secrets/DB_USERNAME
    DB_PASSWORD:
        file: /srv/vxnn/secrets/DB_PASSWORD
    BACKEND_SESSION_KEY_1:
        file: /srv/vxnn/secrets/BACKEND_SESSION_KEY_1
    NGINX_STAGING_AUTH:
        file: /srv/vxnn/secrets/NGINX_STAGING_AUTH
