version: "3"

services:
    backend:
        depends_on:
            - db
    nginx:
        depends_on:
            - backend
            - db
    certbot:
        depends_on:
            - nginx

    worker:
        depends_on:
            - nginx
            - certbot
