version: "3"

services:
    db:
        ports:
            - ${DB_PORT}:${DB_PORT}

    nginx:
        volumes:
            - ./src/nginx/dev-certs:/etc/letsencrypt/live/localhost
            - ./public:/etc/nginx/html
        environment:
            - APP_DOMAIN=localhost
            - BACKEND_SERVICE_NAME=host.docker.internal # localhost on host matchine
